name: Generate podcast Feeds
on: [push]
jobs:
 build:
  runs-on: ununtu-latest
  steps:
   - name: Checkout Repo
     uses: actions/checkout@v3
     
   - name: setup python
     uses: actions/Setup-python@v4
     with:
       python-version: '3.12'
       
   - name: install dependencies
     run: 
       py -m pip install --upgrade pip
       pip install pyyaml
       
   - name: Run Feed Generator
     run: python feed.py
     
   - name: Push Repo
     run: 
       git config user.name github-actions
       git config user.email github-action@github.com
       git add.
       git commit -m "Modified Feed"
       git push
       
